"""Compile schema.yaml → DDL + schema_registry field contracts."""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path
from typing import Any

from domain_foundry_core.clock import now_iso
from domain_foundry_core.packs.models import DomainPack, FieldSpec, link_column
from domain_foundry_core.security.store import connect_rw

_SQL_TYPE = {
    "text": "TEXT",
    "number": "REAL",
    "integer": "INTEGER",
    "boolean": "INTEGER",
    "date": "TEXT",
    "datetime": "TEXT",
    "duration": "REAL",
    "enum": "TEXT",
    "attachment": "TEXT",
    "location": "TEXT",
}

_IDENT_RE = re.compile(r"^[a-z][a-z0-9_]{0,62}$")


def table_name(pack: str, object_type: str) -> str:
    name = f"{pack}__{object_type}"
    if not _IDENT_RE.match(pack) or not _IDENT_RE.match(object_type):
        raise ValueError(f"unsafe table identity: {name}")
    return name


def field_contract(pack: DomainPack) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for obj_name, obj in pack.objects.items():
        fields: dict[str, Any] = {}
        for fname, fspec in obj.fields.items():
            fields[fname] = _field_json(fspec)
        out[obj_name] = {
            "title_field": obj.title_field,
            "fields": fields,
            "links": {k: v.model_dump() for k, v in obj.links.items()},
            "operations": pack.operations.get(obj_name, []),
        }
    return out


def _field_json(fspec: FieldSpec) -> dict[str, Any]:
    d = fspec.model_dump(exclude_none=True)
    return d


def link_columns(
    pack: DomainPack, available_packs: set[str] | None = None
) -> dict[str, list[dict[str, str]]]:
    """Per object, the link columns and the table each one points at.

    ``available_packs`` names the packs whose tables live in the same database.
    A link into a pack that is not there still gets its column, so no data is
    lost, but no foreign key: pointing a constraint at a missing table would
    make every insert fail.
    """
    known = {pack.name} if available_packs is None else {pack.name, *available_packs}
    out: dict[str, list[dict[str, str]]] = {}
    for obj_name, obj in pack.objects.items():
        rows: list[dict[str, str]] = []
        for link_name, link in obj.links.items():
            target_pack, target_object = pack.link_target(link)
            column = link_column(link_name)
            if not _IDENT_RE.match(column):
                raise ValueError(f"unsafe link column: {column}")
            row = {
                "link": link_name,
                "column": column,
                "target_pack": target_pack,
                "target_object": target_object,
                "target": f"{target_pack}.{target_object}",
                "table": "",
            }
            if target_pack in known:
                row["table"] = table_name(target_pack, target_object)
            rows.append(row)
        out[obj_name] = rows
    return out


def compile_ddl(pack: DomainPack, *, available_packs: set[str] | None = None) -> str:
    """Generate additive CREATE TABLE IF NOT EXISTS SQL for pack objects.

    Links compile to a column holding the target row's ``object_uid`` plus a
    real FOREIGN KEY, so a reference to a record that is not there is refused
    by the database. Deleting the target sets the reference back to nothing
    rather than deleting the row that pointed at it.
    """
    lines = ["-- generated by domain_foundry schema compiler", "PRAGMA foreign_keys = ON;", ""]
    links_by_object = link_columns(pack, available_packs)
    for obj_name, obj in pack.objects.items():
        tname = table_name(pack.name, obj_name)
        cols = [
            "id INTEGER PRIMARY KEY AUTOINCREMENT",
            "object_uid TEXT UNIQUE",
            "entry_id TEXT",
            "created_at TEXT NOT NULL",
            "updated_at TEXT NOT NULL",
            "tombstoned INTEGER NOT NULL DEFAULT 0",
        ]
        for fname, fspec in obj.fields.items():
            if not _IDENT_RE.match(fname):
                raise ValueError(f"unsafe field name: {fname}")
            sql_t = _SQL_TYPE.get(fspec.type, "TEXT")
            nullability = " NOT NULL" if fspec.required and fspec.default is None else ""
            cols.append(f"{fname} {sql_t}{nullability}")
        indexes = [f"CREATE INDEX IF NOT EXISTS {tname}_entry_idx ON {tname}(entry_id);"]
        for row in links_by_object.get(obj_name, []):
            if row["table"]:
                cols.append(
                    f"FOREIGN KEY ({row['column']}) REFERENCES {row['table']}(object_uid) "
                    "ON DELETE SET NULL"
                )
            indexes.append(
                f"CREATE INDEX IF NOT EXISTS {tname}_{row['column']}_idx "
                f"ON {tname}({row['column']});"
            )
        lines.append(f"CREATE TABLE IF NOT EXISTS {tname} (")
        lines.append("    " + ",\n    ".join(cols))
        lines.append(");")
        lines.extend(indexes)
        lines.append("")
    return "\n".join(lines)


def installed_pack_names(ledger_db: Path) -> set[str]:
    """Packs recorded as installed, so the compiler knows which tables exist."""
    conn = connect_rw(ledger_db)
    try:
        rows = conn.execute("SELECT name FROM pack_install WHERE active = 1").fetchall()
    except sqlite3.Error:
        return set()
    finally:
        conn.close()
    return {str(row[0]) for row in rows}


def _existing_columns(conn: sqlite3.Connection, tname: str) -> set[str]:
    rows = conn.execute(f'PRAGMA table_info("{tname}")').fetchall()
    return {str(row[1]) for row in rows}


def _apply_additive_columns(conn: sqlite3.Connection, pack: DomainPack) -> list[str]:
    """Add columns a table is missing. Never drops or rewrites anything.

    An existing table keeps its rows. New fields and new link columns arrive as
    nullable columns, which is the only change SQLite can make in place.
    """
    added: list[str] = []
    for obj_name, obj in pack.objects.items():
        tname = table_name(pack.name, obj_name)
        exists = conn.execute(
            "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?", (tname,)
        ).fetchone()
        if not exists:
            continue
        present = _existing_columns(conn, tname)
        for fname, fspec in obj.fields.items():
            if fname in present or not _IDENT_RE.match(fname):
                continue
            sql_t = _SQL_TYPE.get(fspec.type, "TEXT")
            conn.execute(f'ALTER TABLE "{tname}" ADD COLUMN {fname} {sql_t}')
            added.append(f"{tname}.{fname}")
    return added


def uninstall_blockers(pack_name: str, packs: list[DomainPack], domains_db: Path) -> list[str]:
    """Plain messages for records that still point at ``pack_name``.

    Removing a pack whose records other packs point at would break those
    references, so the caller should refuse while this list is not empty.
    """
    blockers: list[str] = []
    if not domains_db.exists():
        return blockers
    conn = connect_rw(domains_db)
    try:
        for other in packs:
            if other.name == pack_name:
                continue
            for obj_name, rows in link_columns(other, {pack_name}).items():
                for row in rows:
                    if row["target_pack"] != pack_name:
                        continue
                    tname = table_name(other.name, obj_name)
                    try:
                        count = conn.execute(
                            f'SELECT COUNT(*) FROM "{tname}" WHERE {row["column"]} IS NOT NULL'
                        ).fetchone()[0]
                    except sqlite3.Error:
                        continue
                    if count:
                        blockers.append(
                            f"{count} {other.name} {obj_name} record"
                            f"{'s' if count != 1 else ''} still point at "
                            f"{row['target']}. Clear the {row['link']} link on "
                            f"those records first, or remove {other.name} too."
                        )
    finally:
        conn.close()
    return blockers


def write_migration(pack: DomainPack, migrations_dir: Path | None = None) -> Path:
    migrations_dir = migrations_dir or (pack.root / "migrations")
    migrations_dir.mkdir(parents=True, exist_ok=True)
    # version from pack major.minor → integer stamp; use sequential file count + 1
    existing = sorted(migrations_dir.glob(f"{pack.name}_*.sql"))
    next_n = 1
    if existing:
        m = re.search(rf"{re.escape(pack.name)}_(\d+)_", existing[-1].name)
        if m:
            next_n = int(m.group(1)) + 1
    path = migrations_dir / f"{pack.name}_{next_n:03d}_schema.sql"
    path.write_text(compile_ddl(pack), encoding="utf-8")
    return path


def apply_pack_schema(pack: DomainPack, domains_db: Path, ledger_db: Path) -> None:
    """Apply compiled DDL to domains.sqlite and register field contracts in ledger."""
    available = installed_pack_names(ledger_db) | {pack.name}
    ddl = compile_ddl(pack, available_packs=available)
    conn = connect_rw(domains_db)
    try:
        _apply_additive_columns(conn, pack)
        conn.executescript(ddl)
        conn.commit()
    finally:
        conn.close()

    contract = field_contract(pack)
    ts = now_iso()
    lconn = connect_rw(ledger_db)
    try:
        for obj_name, obj_contract in contract.items():
            # deactivate prior versions of same object
            lconn.execute(
                """
                UPDATE schema_registry SET active = 0
                WHERE domain = ? AND object_type = ? AND active = 1
                """,
                (pack.name, obj_name),
            )
            # derive integer schema_version from pack semver patch+minor heuristic
            schema_version = _schema_version_int(pack.version)
            lconn.execute(
                """
                INSERT INTO schema_registry (
                    domain, object_type, schema_version, pack_version,
                    field_contract_json, active, created_at, migration_notes
                ) VALUES (?, ?, ?, ?, ?, 1, ?, ?)
                ON CONFLICT(domain, object_type, schema_version) DO UPDATE SET
                    pack_version = excluded.pack_version,
                    field_contract_json = excluded.field_contract_json,
                    active = 1,
                    created_at = excluded.created_at
                """,
                (
                    pack.name,
                    obj_name,
                    schema_version,
                    pack.version,
                    json.dumps(obj_contract, separators=(",", ":")),
                    ts,
                    "compiled from pack schema.yaml",
                ),
            )
        # seed apply_policy from pack (source=pack); leave user overrides alone
        for row in pack.policy.defaults:
            domain = pack.name
            operation = row.operation or "*"
            object_type = row.object_type or "*"
            channel = "*"
            if row.match and "channel" in row.match:
                channel = str(row.match["channel"])
            min_conf = row.min_confidence if row.min_confidence is not None else 0.8
            lconn.execute(
                """
                INSERT INTO apply_policy (
                    domain, operation, object_type, channel, min_confidence,
                    condition_json, action, priority, source
                ) VALUES (?, ?, ?, ?, ?, NULL, ?, 100, 'pack')
                ON CONFLICT(domain, operation, object_type, channel, source) DO UPDATE SET
                    min_confidence = excluded.min_confidence,
                    action = excluded.action
                """,
                (domain, operation, object_type, channel, min_conf, row.action),
            )
        lconn.execute(
            """
            INSERT INTO pack_install (name, version, path, installed_at, active)
            VALUES (?, ?, ?, ?, 1)
            ON CONFLICT(name) DO UPDATE SET
                version = excluded.version,
                path = excluded.path,
                installed_at = excluded.installed_at,
                active = 1
            """,
            (pack.name, pack.version, str(pack.root), ts),
        )
        lconn.commit()
    finally:
        lconn.close()


def _schema_version_int(semver: str) -> int:
    parts = semver.split("+")[0].split("-")[0].split(".")
    major = int(parts[0]) if parts else 0
    minor = int(parts[1]) if len(parts) > 1 else 0
    patch = int(parts[2]) if len(parts) > 2 else 0
    return major * 1_000_000 + minor * 1_000 + patch
