"""Compile schema.yaml → DDL + schema_registry field contracts."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from domain_foundry_core.clock import now_iso
from domain_foundry_core.packs.models import DomainPack, FieldSpec
from domain_foundry_core.security.store import connect_rw

_SQL_TYPE = {
    "text": "TEXT",
    "number": "REAL",
    "integer": "INTEGER",
    "boolean": "INTEGER",
    "date": "TEXT",
    "datetime": "TEXT",
    "duration": "REAL",
    "enum": "TEXT",
    "attachment": "TEXT",
    "location": "TEXT",
}

_IDENT_RE = re.compile(r"^[a-z][a-z0-9_]{0,62}$")


def table_name(pack: str, object_type: str) -> str:
    name = f"{pack}__{object_type}"
    if not _IDENT_RE.match(pack) or not _IDENT_RE.match(object_type):
        raise ValueError(f"unsafe table identity: {name}")
    return name


def field_contract(pack: DomainPack) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for obj_name, obj in pack.objects.items():
        fields: dict[str, Any] = {}
        for fname, fspec in obj.fields.items():
            fields[fname] = _field_json(fspec)
        out[obj_name] = {
            "title_field": obj.title_field,
            "fields": fields,
            "links": {k: v.model_dump() for k, v in obj.links.items()},
            "operations": pack.operations.get(obj_name, []),
        }
    return out


def _field_json(fspec: FieldSpec) -> dict[str, Any]:
    d = fspec.model_dump(exclude_none=True)
    return d


def compile_ddl(pack: DomainPack) -> str:
    """Generate additive CREATE TABLE IF NOT EXISTS SQL for pack objects."""
    lines = ["-- generated by domain_foundry schema compiler", "PRAGMA foreign_keys = ON;", ""]
    for obj_name, obj in pack.objects.items():
        tname = table_name(pack.name, obj_name)
        cols = [
            "id INTEGER PRIMARY KEY AUTOINCREMENT",
            "object_uid TEXT UNIQUE",
            "entry_id TEXT",
            "created_at TEXT NOT NULL",
            "updated_at TEXT NOT NULL",
            "tombstoned INTEGER NOT NULL DEFAULT 0",
        ]
        for fname, fspec in obj.fields.items():
            if not _IDENT_RE.match(fname):
                raise ValueError(f"unsafe field name: {fname}")
            sql_t = _SQL_TYPE.get(fspec.type, "TEXT")
            nullability = " NOT NULL" if fspec.required and fspec.default is None else ""
            cols.append(f"{fname} {sql_t}{nullability}")
        lines.append(f"CREATE TABLE IF NOT EXISTS {tname} (")
        lines.append("    " + ",\n    ".join(cols))
        lines.append(");")
        lines.append(f"CREATE INDEX IF NOT EXISTS {tname}_entry_idx ON {tname}(entry_id);")
        lines.append("")
    return "\n".join(lines)


def write_migration(pack: DomainPack, migrations_dir: Path | None = None) -> Path:
    migrations_dir = migrations_dir or (pack.root / "migrations")
    migrations_dir.mkdir(parents=True, exist_ok=True)
    # version from pack major.minor → integer stamp; use sequential file count + 1
    existing = sorted(migrations_dir.glob(f"{pack.name}_*.sql"))
    next_n = 1
    if existing:
        m = re.search(rf"{re.escape(pack.name)}_(\d+)_", existing[-1].name)
        if m:
            next_n = int(m.group(1)) + 1
    path = migrations_dir / f"{pack.name}_{next_n:03d}_schema.sql"
    path.write_text(compile_ddl(pack), encoding="utf-8")
    return path


def apply_pack_schema(pack: DomainPack, domains_db: Path, ledger_db: Path) -> None:
    """Apply compiled DDL to domains.sqlite and register field contracts in ledger."""
    ddl = compile_ddl(pack)
    conn = connect_rw(domains_db)
    try:
        conn.executescript(ddl)
        conn.commit()
    finally:
        conn.close()

    contract = field_contract(pack)
    ts = now_iso()
    lconn = connect_rw(ledger_db)
    try:
        for obj_name, obj_contract in contract.items():
            # deactivate prior versions of same object
            lconn.execute(
                """
                UPDATE schema_registry SET active = 0
                WHERE domain = ? AND object_type = ? AND active = 1
                """,
                (pack.name, obj_name),
            )
            # derive integer schema_version from pack semver patch+minor heuristic
            schema_version = _schema_version_int(pack.version)
            lconn.execute(
                """
                INSERT INTO schema_registry (
                    domain, object_type, schema_version, pack_version,
                    field_contract_json, active, created_at, migration_notes
                ) VALUES (?, ?, ?, ?, ?, 1, ?, ?)
                ON CONFLICT(domain, object_type, schema_version) DO UPDATE SET
                    pack_version = excluded.pack_version,
                    field_contract_json = excluded.field_contract_json,
                    active = 1,
                    created_at = excluded.created_at
                """,
                (
                    pack.name,
                    obj_name,
                    schema_version,
                    pack.version,
                    json.dumps(obj_contract, separators=(",", ":")),
                    ts,
                    "compiled from pack schema.yaml",
                ),
            )
        # seed apply_policy from pack (source=pack); leave user overrides alone
        for row in pack.policy.defaults:
            domain = pack.name
            operation = row.operation or "*"
            object_type = row.object_type or "*"
            channel = "*"
            if row.match and "channel" in row.match:
                channel = str(row.match["channel"])
            min_conf = row.min_confidence if row.min_confidence is not None else 0.8
            lconn.execute(
                """
                INSERT INTO apply_policy (
                    domain, operation, object_type, channel, min_confidence,
                    condition_json, action, priority, source
                ) VALUES (?, ?, ?, ?, ?, NULL, ?, 100, 'pack')
                ON CONFLICT(domain, operation, object_type, channel, source) DO UPDATE SET
                    min_confidence = excluded.min_confidence,
                    action = excluded.action
                """,
                (domain, operation, object_type, channel, min_conf, row.action),
            )
        lconn.execute(
            """
            INSERT INTO pack_install (name, version, path, installed_at, active)
            VALUES (?, ?, ?, ?, 1)
            ON CONFLICT(name) DO UPDATE SET
                version = excluded.version,
                path = excluded.path,
                installed_at = excluded.installed_at,
                active = 1
            """,
            (pack.name, pack.version, str(pack.root), ts),
        )
        lconn.commit()
    finally:
        lconn.close()


def _schema_version_int(semver: str) -> int:
    parts = semver.split("+")[0].split("-")[0].split(".")
    major = int(parts[0]) if parts else 0
    minor = int(parts[1]) if len(parts) > 1 else 0
    patch = int(parts[2]) if len(parts) > 2 else 0
    return major * 1_000_000 + minor * 1_000 + patch
